import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:image_picker/image_picker.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:permission_handler/permission_handler.dart'
    as ph
    show openAppSettings;
import 'package:share_plus/share_plus.dart';

/// Picks an image from a source (camera / gallery). Hoisted to a top-level
/// typedef so [ShareService] tests can substitute the underlying picker
/// without staging a real plugin.
typedef ImageSourcePicker = Future<XFile?> Function(ImageSource source);

/// Hands a list of files to the native share sheet. Hoisted for DI.
typedef FileShareSink =
    Future<ShareResult> Function(List<XFile> files, {String? text});

/// Requests a runtime permission and returns its post-request status.
typedef PermissionRequester =
    Future<PermissionStatus> Function(Permission permission);

/// Returns the current status of a runtime permission (no prompt).
typedef PermissionStatusReader =
    Future<PermissionStatus> Function(Permission permission);

/// Opens the host platform's app-settings screen so the user can flip the
/// permission toggle. Hoisted for DI — `permission_handler` exposes this
/// as a top-level function (`openAppSettings()`); we wrap it in a typedef
/// so tests can verify the call without staging the platform channel.
typedef AppSettingsOpener = Future<bool> Function();

/// Single source of truth for share-card IO: camera/gallery pick, share
/// sheet handoff, and camera-permission checks.
///
/// Constructor-injected seams cover every platform call so unit tests can
/// run pure-Dart without staging Android/iOS plugin channels. Default
/// implementations delegate to:
///   * `image_picker.ImagePicker().pickImage(...)`
///   * `share_plus.SharePlus.instance.share(ShareParams(...))`
///   * `permission_handler.Permission.camera.request()` / `.status`
class ShareService {
  ShareService({
    ImageSourcePicker? imagePicker,
    FileShareSink? fileShareSink,
    PermissionRequester? permissionRequester,
    PermissionStatusReader? permissionStatusReader,
    AppSettingsOpener? appSettingsOpener,
  }) : _imagePicker = imagePicker ?? _defaultImagePicker,
       _fileShareSink = fileShareSink ?? _defaultFileShareSink,
       _permissionRequester =
           permissionRequester ?? _defaultPermissionRequester,
       _permissionStatusReader =
           permissionStatusReader ?? _defaultPermissionStatusReader,
       _appSettingsOpener = appSettingsOpener ?? _defaultAppSettingsOpener;

  final ImageSourcePicker _imagePicker;
  final FileShareSink _fileShareSink;
  final PermissionRequester _permissionRequester;
  final PermissionStatusReader _permissionStatusReader;
  final AppSettingsOpener _appSettingsOpener;

  /// Open the platform camera and return the captured image, or `null` if
  /// the user cancelled or the platform denied access. Callers should
  /// gate this on [requestCameraPermission] for graceful denial UX —
  /// this method itself does NOT prompt for permission.
  Future<XFile?> pickFromCamera() => _imagePicker(ImageSource.camera);

  /// Open the gallery picker and return the selected image, or `null` if
  /// the user dismissed without selecting. Gallery picks on Android 13+
  /// route through the system photo picker, which does not require a
  /// runtime media-images permission.
  Future<XFile?> pickFromGallery() => _imagePicker(ImageSource.gallery);

  /// Hand [file] to the native share sheet. Optional [text] is appended
  /// to the share payload (caption / link / promo blurb). The returned
  /// [ShareResult] tells the caller whether the user shared, dismissed,
  /// or hit a platform error.
  Future<ShareResult> share(XFile file, {String? text}) {
    return _fileShareSink(<XFile>[file], text: text);
  }

  /// Prompt the user for camera permission. Returns the post-prompt
  /// status: [PermissionStatus.granted] / [PermissionStatus.denied] /
  /// [PermissionStatus.permanentlyDenied] / etc. Never throws on user
  /// denial — denial is a status, not an exception.
  ///
  /// **Web bypass — cluster `permission-handler-web-silent-failure`.**
  /// `permission_handler`'s web delegate (`permission_handler_html`)
  /// ships behind a MethodChannel
  /// (`flutter.baseflow.com/permissions/methods`) registered via the
  /// generated `web_plugin_registrant.dart`. That registrant is
  /// regenerated by `flutter build web` based on a hash of the resolved
  /// plugin set — and historically the invalidation has been flaky on
  /// pubspec churn (a stale cache lets the channel call fall through to
  /// the default MethodChannel handler with no implementation, throwing
  /// `MissingPluginException` and breaking the share flow silently).
  /// On web the browser-level camera UX is handled inline by
  /// `getUserMedia` / file-input gestures anyway — there is no OS-level
  /// permission for us to surface to the user, and `permission_handler`'s
  /// `openAppSettings()` is a no-op there. We short-circuit on web
  /// returning [PermissionStatus.granted] so the rest of the flow
  /// proceeds without depending on the registrant.
  Future<PermissionStatus> requestCameraPermission() {
    if (kIsWeb) return Future.value(PermissionStatus.granted);
    return _permissionRequester(Permission.camera);
  }

  /// Read the current camera-permission status without prompting. Use
  /// this before `pickFromCamera` to decide whether to call
  /// [requestCameraPermission] or jump straight to the picker.
  ///
  /// **Web bypass.** Same rationale as [requestCameraPermission] —
  /// `permission_handler`'s web path depends on the generated plugin
  /// registrant being current, which is fragile across `flutter build`
  /// cache invalidations. The browser owns the camera-permission UX on
  /// web; we return [PermissionStatus.granted] so [ShareSheet] renders
  /// all three rows (camera row is only hidden when the OS reports
  /// `permanentlyDenied`, which web never reaches).
  Future<PermissionStatus> cameraPermissionStatus() {
    if (kIsWeb) return Future.value(PermissionStatus.granted);
    return _permissionStatusReader(Permission.camera);
  }

  /// Open the platform app-settings screen so the user can flip a denied
  /// permission. Used by the share preview's permanently-denied recovery
  /// path. Returns `true` if the settings screen opened successfully.
  ///
  /// **Web bypass.** `permission_handler_html` returns
  /// `SynchronousFuture(false)` here anyway — there is no app-settings
  /// surface on web. We short-circuit to keep the same observable
  /// behavior without depending on the plugin registrant being
  /// registered.
  Future<bool> openAppSettings() {
    if (kIsWeb) return Future.value(false);
    return _appSettingsOpener();
  }

  // --------------------------------------------------------------------
  // Default platform implementations.
  // --------------------------------------------------------------------

  static Future<XFile?> _defaultImagePicker(ImageSource source) {
    return ImagePicker().pickImage(source: source);
  }

  static Future<ShareResult> _defaultFileShareSink(
    List<XFile> files, {
    String? text,
  }) {
    // share_plus 12.x API: the static `Share.shareXFiles` was deprecated in
    // favor of `SharePlus.instance.share` with a `ShareParams` builder.
    return SharePlus.instance.share(ShareParams(files: files, text: text));
  }

  static Future<PermissionStatus> _defaultPermissionRequester(
    Permission permission,
  ) {
    return permission.request();
  }

  static Future<PermissionStatus> _defaultPermissionStatusReader(
    Permission permission,
  ) {
    return permission.status;
  }

  // The top-level `openAppSettings()` from `permission_handler` is shadowed
  // by our same-named instance method, so reach for it via the package's
  // namespace prefix. Wrapping it in a function reference keeps the typedef
  // contract clean.
  static Future<bool> _defaultAppSettingsOpener() => ph.openAppSettings();
}
