import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:repsaga/features/rpg/domain/xp_calculator.dart';

/// Loads the JSON fixtures generated by
/// `test/fixtures/generate_rpg_fixtures.py`. The fixture is the
/// **single source of truth** for Dart-vs-Python parity. If a constant
/// changes here without regenerating the fixture, this test fails — that
/// is intentional.
Map<String, dynamic> _loadFixtures() {
  final file = File('test/fixtures/rpg_xp_fixtures.json');
  if (!file.existsSync()) {
    throw StateError(
      'rpg_xp_fixtures.json missing — run '
      '`python test/fixtures/generate_rpg_fixtures.py` first.',
    );
  }
  return json.decode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Tolerance for double parity. Volume_load^0.60 with strength_mult and
/// novelty introduces some float rounding; 1e-9 absolute is far tighter
/// than anything user-observable but loose enough that x86_64 vs ARM
/// double-rounding doesn't false-fail.
const double _eps = 1e-9;

void main() {
  late final Map<String, dynamic> fixtures;

  setUpAll(() {
    fixtures = _loadFixtures();
  });

  group('Constants parity with Python sim', () {
    test('volume_exponent == 0.60 (Phase 24d propagation)', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.volumeExponent, meta['volume_exponent']);
      expect(XpCalculator.volumeExponent, 0.60);
    });

    test('novelty_denominator == 15', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.noveltyDenominator, meta['novelty_denominator']);
    });

    test('weekly_cap_sets == 15 with 0.3 over-cap multiplier '
        '(Phase 24d propagation)', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.weeklyCapSets, meta['weekly_cap_sets']);
      expect(XpCalculator.overCapMultiplier, meta['over_cap_multiplier']);
      expect(XpCalculator.weeklyCapSets, 15.0);
      expect(XpCalculator.overCapMultiplier, 0.3);
    });

    test('strength_mult_floor == 0.40', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.strengthMultFloor, meta['strength_mult_floor']);
    });
  });

  group('intensityForReps — table parity', () {
    test('every reps boundary returns the spec multiplier', () {
      final cases = fixtures['intensity_lookup'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final reps = c['reps'] as int;
        final expected = (c['intensity_mult'] as num).toDouble();
        expect(
          XpCalculator.intensityForReps(reps),
          closeTo(expected, _eps),
          reason: 'reps=$reps should yield $expected',
        );
      }
    });

    test('reps below 1 fall back to 1.0', () {
      expect(XpCalculator.intensityForReps(0), 1.0);
      expect(XpCalculator.intensityForReps(-5), 1.0);
    });

    test('reps boundary semantics: 4 reps lands in the >=3 row (1.25)', () {
      expect(XpCalculator.intensityForReps(4), 1.25);
    });

    test('reps boundary semantics: 8 reps lands in the >=8 row (1.00)', () {
      expect(XpCalculator.intensityForReps(8), 1.00);
    });

    test('reps boundary semantics: 13 reps lands in the >=12 row (0.95)', () {
      expect(XpCalculator.intensityForReps(13), 0.95);
    });

    test('reps 25+ saturate at 0.80', () {
      expect(XpCalculator.intensityForReps(25), 0.80);
      expect(XpCalculator.intensityForReps(100), 0.80);
    });
  });

  group('volumeLoad + baseXp — parity', () {
    test('every fixture case matches', () {
      final cases = fixtures['volume_load'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final w = (c['weight_kg'] as num).toDouble();
        final r = c['reps'] as int;
        final vlExpected = (c['volume_load'] as num).toDouble();
        final baseExpected = (c['base_xp'] as num).toDouble();
        final vl = XpCalculator.volumeLoad(weightKg: w, reps: r);
        expect(
          vl,
          closeTo(vlExpected, _eps),
          reason: 'volume_load(w=$w, r=$r)',
        );
        expect(
          XpCalculator.baseXp(vl),
          closeTo(baseExpected, _eps),
          reason: 'base_xp(vl=$vl)',
        );
      }
    });

    test('volume_load floor is 1.0', () {
      expect(XpCalculator.volumeLoad(weightKg: 0, reps: 8), 1.0);
      expect(XpCalculator.volumeLoad(weightKg: 0.1, reps: 1), 1.0);
    });

    test('reps < 1 returns the floor', () {
      expect(XpCalculator.volumeLoad(weightKg: 100, reps: 0), 1.0);
      expect(XpCalculator.volumeLoad(weightKg: 100, reps: -1), 1.0);
    });
  });

  group('strengthMult — clamp + floor', () {
    test('every fixture case matches', () {
      final cases = fixtures['strength_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final w = (c['weight_kg'] as num).toDouble();
        final p = (c['peak_load'] as num).toDouble();
        final expected = (c['strength_mult'] as num).toDouble();
        expect(
          XpCalculator.strengthMult(weightKg: w, peakLoad: p),
          closeTo(expected, _eps),
          reason: 'strengthMult(weight=$w, peak=$p)',
        );
      }
    });

    test('weight at peak yields exactly 1.0', () {
      expect(XpCalculator.strengthMult(weightKg: 100, peakLoad: 100), 1.0);
    });

    test('weight above peak clamps to 1.0', () {
      expect(XpCalculator.strengthMult(weightKg: 110, peakLoad: 100), 1.0);
    });

    test('weight below floor floors to 0.4', () {
      expect(XpCalculator.strengthMult(weightKg: 30, peakLoad: 100), 0.4);
      expect(XpCalculator.strengthMult(weightKg: 1, peakLoad: 100), 0.4);
    });

    test('peak == 0 returns 1.0 (no prior peak — divide-by-zero guard)', () {
      expect(XpCalculator.strengthMult(weightKg: 50, peakLoad: 0), 1.0);
      expect(XpCalculator.strengthMult(weightKg: 0, peakLoad: 0), 1.0);
    });
  });

  group('noveltyMult — exp decay', () {
    test('every fixture case matches', () {
      final cases = fixtures['novelty_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final sv = (c['session_volume_for_body_part'] as num).toDouble();
        final expected = (c['novelty_mult'] as num).toDouble();
        expect(
          XpCalculator.noveltyMult(sv),
          closeTo(expected, _eps),
          reason: 'noveltyMult(sv=$sv)',
        );
      }
    });

    test('zero session volume returns 1.0', () {
      expect(XpCalculator.noveltyMult(0), 1.0);
    });

    test('session volume of 15 returns ~0.368 (e^-1)', () {
      expect(XpCalculator.noveltyMult(15), closeTo(0.367879441, 1e-6));
    });

    test('negative input is clamped to 1.0 (defensive)', () {
      expect(XpCalculator.noveltyMult(-5), 1.0);
    });
  });

  group('capMult — weekly cap', () {
    test('every fixture case matches', () {
      final cases = fixtures['cap_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final wv = (c['weekly_volume_for_body_part'] as num).toDouble();
        final expected = (c['cap_mult'] as num).toDouble();
        expect(
          XpCalculator.capMult(wv),
          expected,
          reason: 'capMult(weeklyVolume=$wv)',
        );
      }
    });

    test('exactly 15 sets triggers the cap (>= boundary, Phase 24d)', () {
      expect(XpCalculator.capMult(15.0), 0.3);
      // Just below the boundary stays at 1.0
      expect(XpCalculator.capMult(14.999), 1.0);
    });
  });

  group('computeSetXp — end-to-end parity', skip:
      'Phase 29 PR 2 restores. PR 1 regenerated the Python fixture against the '
      'Phase 29 v2 formula (5 refinements + #6 piecewise + #29.6 abs_strength_premium); '
      'Dart XpCalculator is still on Phase 24d. The end-to-end parity test fails by '
      'design until Dart is ported in PR 2. Once Dart matches the fixture within '
      '1e-4 absolute, remove this skip.', () {
    test('every set_xp fixture case matches all components within $_eps', () {
      final cases = fixtures['set_xp_examples'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final inputs = c['inputs'] as Map<String, dynamic>;
        final components = c['components'] as Map<String, dynamic>;

        final result = XpCalculator.computeSetXp(
          weightKg: (inputs['weight_kg'] as num).toDouble(),
          reps: inputs['reps'] as int,
          peakLoad: (inputs['peak_load'] as num).toDouble(),
          sessionVolumeForBodyPart:
              (inputs['session_volume_for_body_part'] as num).toDouble(),
          weeklyVolumeForBodyPart:
              (inputs['weekly_volume_for_body_part'] as num).toDouble(),
          // Phase 24a Phase F: read the per-scenario difficulty_mult from the
          // regenerated fixture. Each scenario in `set_xp_examples` carries
          // its own multiplier (per-exercise curated values from migration
          // 00053, plus explicit floor/ceiling and user-created defaults).
          // The expected `set_xp` already accounts for it.
          difficultyMult: (inputs['difficulty_mult'] as num).toDouble(),
        );

        final name = c['name'] as String;
        expect(
          result.volumeLoad,
          closeTo((components['volume_load'] as num).toDouble(), _eps),
          reason: '[$name] volume_load',
        );
        expect(
          result.baseXp,
          closeTo((components['base_xp'] as num).toDouble(), _eps),
          reason: '[$name] base_xp',
        );
        expect(
          result.intensityMult,
          closeTo((components['intensity_mult'] as num).toDouble(), _eps),
          reason: '[$name] intensity_mult',
        );
        expect(
          result.strengthMult,
          closeTo((components['strength_mult'] as num).toDouble(), _eps),
          reason: '[$name] strength_mult',
        );
        expect(
          result.noveltyMult,
          closeTo((components['novelty_mult'] as num).toDouble(), _eps),
          reason: '[$name] novelty_mult',
        );
        expect(
          result.capMult,
          closeTo((components['cap_mult'] as num).toDouble(), _eps),
          reason: '[$name] cap_mult',
        );
        expect(
          result.setXp,
          closeTo((c['set_xp'] as num).toDouble(), _eps),
          reason: '[$name] total set_xp',
        );
      }
    });

    test(
      'peak advances the set still earns 1.0× (since we floor peak to weight)',
      () {
        // When weight > recorded peak, the calculator returns 1.0 (the
        // record_set_xp RPC is responsible for advancing the peak BEFORE
        // computing strength_mult; we test that the calculator is consistent
        // with peak == weight). This mirrors the SQL contract.
        final r = XpCalculator.computeSetXp(
          weightKg: 110,
          reps: 5,
          peakLoad: 100, // stale peak — RPC would advance to 110 first
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
          difficultyMult: 1.0,
        );
        // 110/100 = 1.1, clamped to 1.0
        expect(r.strengthMult, 1.0);
      },
    );

    test(
      'toJson() produces the breakdown shape stored on xp_events.payload',
      () {
        final r = XpCalculator.computeSetXp(
          weightKg: 100,
          reps: 5,
          peakLoad: 100,
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
          difficultyMult: 1.0,
        );
        final json = r.toJson();
        expect(json.keys.toSet(), {
          'volume_load',
          'base_xp',
          'intensity_mult',
          'strength_mult',
          'novelty_mult',
          'cap_mult',
          'difficulty_mult',
          'set_xp',
        });
        expect(json['set_xp'], r.setXp);
        expect(json['difficulty_mult'], r.difficultyMult);
      },
    );
  });

  group('Boundary + edge cases', () {
    test(
      'zero weight + zero reps → set_xp = 1.0^0.60 × 1 × 1 × 1 × 1 × 1 = 1.0',
      () {
        final r = XpCalculator.computeSetXp(
          weightKg: 0,
          reps: 0,
          peakLoad: 0,
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
          difficultyMult: 1.0,
        );
        expect(r.volumeLoad, 1.0);
        expect(r.baseXp, 1.0);
        expect(r.setXp, 1.0); // 1 × 1 × 1 × 1 × 1 × 1
      },
    );

    test('massive weight does not produce infinity or NaN', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 9999,
        reps: 20,
        peakLoad: 9999,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.0,
      );
      expect(r.setXp.isFinite, isTrue);
      expect(r.setXp, greaterThan(0));
    });

    test('past the weekly cap with high session volume compounds', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 5,
        peakLoad: 100,
        sessionVolumeForBodyPart: 30, // deep into novelty decay
        weeklyVolumeForBodyPart: 30, // past cap
        difficultyMult: 1.0,
      );
      // novelty = exp(-2) ≈ 0.1353, cap = 0.3 (Phase 24d) → set_xp << base
      final base = XpCalculator.baseXp(
        XpCalculator.volumeLoad(weightKg: 100, reps: 5),
      );
      expect(r.setXp, lessThan(base * 0.10));
    });

    test('all multipliers at unity → set_xp == base_xp × intensity', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8, // intensity 1.0
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.0,
      );
      expect(r.intensityMult, 1.0);
      expect(r.strengthMult, 1.0);
      expect(r.noveltyMult, 1.0);
      expect(r.capMult, 1.0);
      expect(r.difficultyMult, 1.0);
      expect(r.setXp, closeTo(r.baseXp, _eps));
    });
  });

  // ---------------------------------------------------------------------------
  // Phase 24a — difficulty_mult parameter semantics
  //
  // These tests are NOT fixture-driven: they pin the multiplier contract
  // independent of the fixture. They are the canary that catches a Phase D
  // (SQL RPC) or Phase E (Python sim + fixture regen) drift later.
  // ---------------------------------------------------------------------------
  group('difficultyMult — parameter semantics', () {
    /// Same inputs at all three difficulty values must scale linearly:
    /// set_xp(d) / set_xp(1.0) == d. This pins difficulty_mult as the final,
    /// purely-multiplicative factor in the chain (no clamp inside
    /// `computeSetXp`, no interaction with other multipliers).
    test('at ceiling (1.25) produces 1.25× the XP of the same set at 1.0', () {
      final baseline = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.0,
      );
      final ceiling = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.25,
      );
      expect(ceiling.difficultyMult, 1.25);
      expect(
        ceiling.setXp,
        closeTo(baseline.setXp * 1.25, _eps),
        reason:
            'difficulty_mult must apply as a final linear scalar; '
            'baseline=${baseline.setXp}, ceiling=${ceiling.setXp}, '
            'expected ratio 1.25, got ${ceiling.setXp / baseline.setXp}',
      );
      // Other components unchanged — the multiplier touches setXp only.
      expect(ceiling.volumeLoad, baseline.volumeLoad);
      expect(ceiling.baseXp, baseline.baseXp);
      expect(ceiling.intensityMult, baseline.intensityMult);
      expect(ceiling.strengthMult, baseline.strengthMult);
      expect(ceiling.noveltyMult, baseline.noveltyMult);
      expect(ceiling.capMult, baseline.capMult);
    });

    test('at floor (0.85) produces 0.85× the XP of the same set at 1.0', () {
      final baseline = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.0,
      );
      final floor = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 0.85,
      );
      expect(floor.difficultyMult, 0.85);
      expect(
        floor.setXp,
        closeTo(baseline.setXp * 0.85, _eps),
        reason:
            'baseline=${baseline.setXp}, floor=${floor.setXp}, '
            'expected ratio 0.85, got ${floor.setXp / baseline.setXp}',
      );
    });

    /// Default-1.0 invariant: a user-created exercise (or any unmapped
    /// default before Phase B's curated UPDATE) reads the column default
    /// 1.0 and must produce the **same** set_xp the formula would
    /// produce without difficulty_mult ever existing. This is the
    /// "no behavior change for unmapped exercises" pin.
    test(
      'difficultyMult: 1.0 produces XP byte-identical to the pre-24a chain',
      () {
        // Hand-compute the pre-24a chain explicitly so this test does NOT
        // delegate to computeSetXp itself (which would tautologically pass
        // even if difficulty_mult silently broke).
        const weight = 80.0;
        const reps = 5;
        const peak = 100.0;
        const sessionVol = 2.5;
        const weeklyVol = 8.0;

        final vl = XpCalculator.volumeLoad(weightKg: weight, reps: reps);
        final base = XpCalculator.baseXp(vl);
        final intensity = XpCalculator.intensityForReps(reps);
        final strength = XpCalculator.strengthMult(
          weightKg: weight,
          peakLoad: peak,
        );
        final novelty = XpCalculator.noveltyMult(sessionVol);
        final cap = XpCalculator.capMult(weeklyVol);
        final pre24aSetXp = base * intensity * strength * novelty * cap;

        final r = XpCalculator.computeSetXp(
          weightKg: weight,
          reps: reps,
          peakLoad: peak,
          sessionVolumeForBodyPart: sessionVol,
          weeklyVolumeForBodyPart: weeklyVol,
          difficultyMult: 1.0,
        );

        expect(r.difficultyMult, 1.0);
        expect(
          r.setXp,
          closeTo(pre24aSetXp, _eps),
          reason:
              'difficulty_mult: 1.0 must be a no-op; '
              'pre-24a chain = $pre24aSetXp, computeSetXp = ${r.setXp}',
        );
      },
    );

    test('floor and ceiling constants match the migration CHECK range', () {
      expect(XpCalculator.difficultyMultFloor, 0.85);
      expect(XpCalculator.difficultyMultCeiling, 1.25);
    });
  });
}
