import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:repsaga/features/rpg/domain/implied_tier.dart';
import 'package:repsaga/features/rpg/domain/xp_calculator.dart';

/// Loads the JSON fixtures generated by
/// `test/fixtures/generate_rpg_fixtures.py`. The fixture is the
/// **single source of truth** for Dart-vs-Python parity. If a constant
/// changes here without regenerating the fixture, this test fails — that
/// is intentional.
Map<String, dynamic> _loadFixtures() {
  final file = File('test/fixtures/rpg_xp_fixtures.json');
  if (!file.existsSync()) {
    throw StateError(
      'rpg_xp_fixtures.json missing — run '
      '`python test/fixtures/generate_rpg_fixtures.py` first.',
    );
  }
  return json.decode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Tolerance for double parity. Volume_load^0.60 with strength_mult and
/// novelty introduces some float rounding; 1e-9 absolute is far tighter
/// than anything user-observable but loose enough that x86_64 vs ARM
/// double-rounding doesn't false-fail.
const double _eps = 1e-9;

void main() {
  late final Map<String, dynamic> fixtures;

  setUpAll(() {
    fixtures = _loadFixtures();
  });

  group('Constants parity with Python sim', () {
    test('volume_exponent == 0.60 (Phase 24d propagation)', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.volumeExponent, meta['volume_exponent']);
      expect(XpCalculator.volumeExponent, 0.60);
    });

    test('novelty_denominator == 15', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.noveltyDenominator, meta['novelty_denominator']);
    });

    test('weekly_cap_sets == 15 with 0.3 over-cap multiplier '
        '(Phase 24d propagation)', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.weeklyCapSets, meta['weekly_cap_sets']);
      expect(XpCalculator.overCapMultiplier, meta['over_cap_multiplier']);
      expect(XpCalculator.weeklyCapSets, 15.0);
      expect(XpCalculator.overCapMultiplier, 0.3);
    });

    test('strength_mult_floor == 0.40', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.strengthMultFloor, meta['strength_mult_floor']);
    });
  });

  group('intensityForReps — table parity', () {
    test('every reps boundary returns the spec multiplier', () {
      final cases = fixtures['intensity_lookup'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final reps = c['reps'] as int;
        final expected = (c['intensity_mult'] as num).toDouble();
        expect(
          XpCalculator.intensityForReps(reps),
          closeTo(expected, _eps),
          reason: 'reps=$reps should yield $expected',
        );
      }
    });

    test('reps below 1 fall back to 1.0', () {
      expect(XpCalculator.intensityForReps(0), 1.0);
      expect(XpCalculator.intensityForReps(-5), 1.0);
    });

    test('reps boundary semantics: 4 reps lands in the >=3 row (1.25)', () {
      expect(XpCalculator.intensityForReps(4), 1.25);
    });

    test('reps boundary semantics: 8 reps lands in the >=8 row (1.00)', () {
      expect(XpCalculator.intensityForReps(8), 1.00);
    });

    test('reps boundary semantics: 13 reps lands in the >=12 row (0.95)', () {
      expect(XpCalculator.intensityForReps(13), 0.95);
    });

    test('reps 25+ saturate at 0.80', () {
      expect(XpCalculator.intensityForReps(25), 0.80);
      expect(XpCalculator.intensityForReps(100), 0.80);
    });
  });

  group('volumeLoad + baseXp — parity', () {
    test('every fixture case matches', () {
      final cases = fixtures['volume_load'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final w = (c['weight_kg'] as num).toDouble();
        final r = c['reps'] as int;
        final vlExpected = (c['volume_load'] as num).toDouble();
        final baseExpected = (c['base_xp'] as num).toDouble();
        final vl = XpCalculator.volumeLoad(weightKg: w, reps: r);
        expect(
          vl,
          closeTo(vlExpected, _eps),
          reason: 'volume_load(w=$w, r=$r)',
        );
        expect(
          XpCalculator.baseXp(vl),
          closeTo(baseExpected, _eps),
          reason: 'base_xp(vl=$vl)',
        );
      }
    });

    test('volume_load floor is 1.0', () {
      expect(XpCalculator.volumeLoad(weightKg: 0, reps: 8), 1.0);
      expect(XpCalculator.volumeLoad(weightKg: 0.1, reps: 1), 1.0);
    });

    test('reps < 1 returns the floor', () {
      expect(XpCalculator.volumeLoad(weightKg: 100, reps: 0), 1.0);
      expect(XpCalculator.volumeLoad(weightKg: 100, reps: -1), 1.0);
    });
  });

  group('strengthMult — clamp + floor', () {
    test('every fixture case matches', () {
      final cases = fixtures['strength_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final w = (c['weight_kg'] as num).toDouble();
        final p = (c['peak_load'] as num).toDouble();
        final expected = (c['strength_mult'] as num).toDouble();
        expect(
          XpCalculator.strengthMult(weightKg: w, peakLoad: p),
          closeTo(expected, _eps),
          reason: 'strengthMult(weight=$w, peak=$p)',
        );
      }
    });

    test('weight at peak yields exactly 1.0', () {
      expect(XpCalculator.strengthMult(weightKg: 100, peakLoad: 100), 1.0);
    });

    test('weight above peak clamps to 1.0', () {
      expect(XpCalculator.strengthMult(weightKg: 110, peakLoad: 100), 1.0);
    });

    test('weight below floor floors to 0.4', () {
      expect(XpCalculator.strengthMult(weightKg: 30, peakLoad: 100), 0.4);
      expect(XpCalculator.strengthMult(weightKg: 1, peakLoad: 100), 0.4);
    });

    test('peak == 0 returns 1.0 (no prior peak — divide-by-zero guard)', () {
      expect(XpCalculator.strengthMult(weightKg: 50, peakLoad: 0), 1.0);
      expect(XpCalculator.strengthMult(weightKg: 0, peakLoad: 0), 1.0);
    });
  });

  group('noveltyMult — exp decay', () {
    test('every fixture case matches', () {
      final cases = fixtures['novelty_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final sv = (c['session_volume_for_body_part'] as num).toDouble();
        final expected = (c['novelty_mult'] as num).toDouble();
        expect(
          XpCalculator.noveltyMult(sv),
          closeTo(expected, _eps),
          reason: 'noveltyMult(sv=$sv)',
        );
      }
    });

    test('zero session volume returns 1.0', () {
      expect(XpCalculator.noveltyMult(0), 1.0);
    });

    test('session volume of 15 returns ~0.368 (e^-1)', () {
      expect(XpCalculator.noveltyMult(15), closeTo(0.367879441, 1e-6));
    });

    test('negative input is clamped to 1.0 (defensive)', () {
      expect(XpCalculator.noveltyMult(-5), 1.0);
    });
  });

  group('capMult — weekly cap', () {
    test('every fixture case matches', () {
      final cases = fixtures['cap_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final wv = (c['weekly_volume_for_body_part'] as num).toDouble();
        final expected = (c['cap_mult'] as num).toDouble();
        expect(
          XpCalculator.capMult(wv),
          expected,
          reason: 'capMult(weeklyVolume=$wv)',
        );
      }
    });

    test('exactly 15 sets triggers the cap (>= boundary, Phase 24d)', () {
      expect(XpCalculator.capMult(15.0), 0.3);
      // Just below the boundary stays at 1.0
      expect(XpCalculator.capMult(14.999), 1.0);
    });
  });

  group('computeSetXp — end-to-end parity', () {
    test('every set_xp fixture case matches all components within $_eps', () {
      final cases = fixtures['set_xp_examples'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final inputs = c['inputs'] as Map<String, dynamic>;
        final components = c['components'] as Map<String, dynamic>;

        final result = XpCalculator.computeSetXp(
          weightKg: (inputs['weight_kg'] as num).toDouble(),
          reps: inputs['reps'] as int,
          peakLoad: (inputs['peak_load'] as num).toDouble(),
          sessionVolumeForBodyPart:
              (inputs['session_volume_for_body_part'] as num).toDouble(),
          weeklyVolumeForBodyPart:
              (inputs['weekly_volume_for_body_part'] as num).toDouble(),
          // Phase 24a Phase F: read the per-scenario difficulty_mult from the
          // regenerated fixture. Each scenario in `set_xp_examples` carries
          // its own multiplier (per-exercise curated values from migration
          // 00053, plus explicit floor/ceiling and user-created defaults).
          // The expected `set_xp` already accounts for it.
          difficultyMult: (inputs['difficulty_mult'] as num).toDouble(),
        );

        final name = c['name'] as String;
        expect(
          result.volumeLoad,
          closeTo((components['volume_load'] as num).toDouble(), _eps),
          reason: '[$name] volume_load',
        );
        expect(
          result.baseXp,
          closeTo((components['base_xp'] as num).toDouble(), _eps),
          reason: '[$name] base_xp',
        );
        expect(
          result.intensityMult,
          closeTo((components['intensity_mult'] as num).toDouble(), _eps),
          reason: '[$name] intensity_mult',
        );
        expect(
          result.strengthMult,
          closeTo((components['strength_mult'] as num).toDouble(), _eps),
          reason: '[$name] strength_mult',
        );
        expect(
          result.noveltyMult,
          closeTo((components['novelty_mult'] as num).toDouble(), _eps),
          reason: '[$name] novelty_mult',
        );
        expect(
          result.capMult,
          closeTo((components['cap_mult'] as num).toDouble(), _eps),
          reason: '[$name] cap_mult',
        );
        expect(
          result.setXp,
          closeTo((c['set_xp'] as num).toDouble(), _eps),
          reason: '[$name] total set_xp',
        );
      }
    });

    test(
      'peak advances the set still earns 1.0× (since we floor peak to weight)',
      () {
        // When weight > recorded peak, the calculator returns 1.0 (the
        // record_set_xp RPC is responsible for advancing the peak BEFORE
        // computing strength_mult; we test that the calculator is consistent
        // with peak == weight). This mirrors the SQL contract.
        final r = XpCalculator.computeSetXp(
          weightKg: 110,
          reps: 5,
          peakLoad: 100, // stale peak — RPC would advance to 110 first
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
          difficultyMult: 1.0,
        );
        // 110/100 = 1.1, clamped to 1.0
        expect(r.strengthMult, 1.0);
      },
    );

    test(
      'toJson() produces the breakdown shape stored on xp_events.payload',
      () {
        final r = XpCalculator.computeSetXp(
          weightKg: 100,
          reps: 5,
          peakLoad: 100,
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
          difficultyMult: 1.0,
        );
        final json = r.toJson();
        expect(json.keys.toSet(), {
          'volume_load',
          'base_xp',
          'intensity_mult',
          'strength_mult',
          'novelty_mult',
          'cap_mult',
          'difficulty_mult',
          // Phase 29 v2 + 29.6 additions — present even when their inputs
          // are neutral (multiplier = 1.0) so the payload shape is stable.
          'tier_diff_mult',
          'abs_strength_premium',
          'overload_mult',
          'frequency_mult',
          'implied_tier',
          'near_failure',
          // Phase Vitality-3 — the strength conditioning gate factor; present
          // even when neutral (1.0) so the payload shape stays stable.
          'vitality_mult',
          'set_xp',
        });
        expect(json['set_xp'], r.setXp);
        expect(json['difficulty_mult'], r.difficultyMult);
        // Phase 29 v2 neutral chain: every new multiplier defaults to 1.0
        // when its corresponding input is omitted.
        expect(json['tier_diff_mult'], 1.0);
        expect(json['abs_strength_premium'], 1.0);
        expect(json['overload_mult'], 1.0);
        expect(json['frequency_mult'], 1.0);
        expect(json['implied_tier'], 0.0);
        expect(json['near_failure'], false);
        // Phase Vitality-3 neutral default — the gate is a no-op unless the
        // caller passes a per-bp vitalityMult.
        expect(json['vitality_mult'], 1.0);
      },
    );

    // -------------------------------------------------------------------------
    // Regression test — PR #252 payload shape parity fix
    //
    // The SQL RPCs (record_set_xp + record_session_xp_batch) were missing
    // `novelty_mult` and `cap_mult` from their `xp_events.payload` jsonb
    // objects. The fix added `v_dom_novelty` and `v_dom_cap` captures
    // inside the per-attribution-key loop and emitted them into the payload.
    //
    // These tests pin:
    //   1. novelty_mult and cap_mult are ALWAYS present in toJson() output,
    //      even at neutral values (session_vol = 0 → novelty = 1.0).
    //   2. novelty_mult and cap_mult carry the CORRECT non-trivial values
    //      when the inputs are non-zero (i.e., they are not stuck at 1.0
    //      due to a missing capture in the per-attribution loop).
    //   3. The full key set of Dart toJson() matches the expected SQL payload
    //      shape — neither side may drop a key the other emits.
    //
    // If someone re-removes novelty_mult or cap_mult from the loop capture,
    // the test at (2) would silently pass only if the value defaults to 1.0.
    // Test (2) uses a non-zero session_vol precisely to force novelty < 1.0,
    // making the absence of the value observable.
    // -------------------------------------------------------------------------
    test(
      'toJson() — novelty_mult and cap_mult are present and non-trivial '
      'when session volume is non-zero (regression PR#252 payload parity)',
      () {
        // Session volume of 15 sets → novelty_mult = exp(-1) ≈ 0.3679,
        // well below 1.0. If the dominant-BP capture was missing from the
        // per-attribution loop (the pre-fix bug), the field would either be
        // absent or stuck at 1.0 (the initial value).
        final r = XpCalculator.computeSetXp(
          weightKg: 100,
          reps: 5,
          peakLoad: 100,
          sessionVolumeForBodyPart: 15, // non-zero → novelty < 1.0
          weeklyVolumeForBodyPart: 0,
          difficultyMult: 1.0,
        );
        final json = r.toJson();

        // Both keys must be present.
        expect(
          json.containsKey('novelty_mult'),
          isTrue,
          reason:
              'novelty_mult must be in xp_events payload (PR#252 fix). '
              'If missing, the SQL→Dart payload shape parity is broken.',
        );
        expect(
          json.containsKey('cap_mult'),
          isTrue,
          reason: 'cap_mult must be in xp_events payload (PR#252 fix).',
        );

        // novelty_mult must reflect the actual non-trivial computation,
        // not the defaulted neutral value 1.0. At sv=15: exp(-15/15)=exp(-1).
        expect(
          (json['novelty_mult'] as double),
          closeTo(XpCalculator.noveltyMult(15), 1e-9),
          reason:
              'novelty_mult in payload must carry the computed dominant-BP '
              'value (≈0.368), not a stale 1.0 initializer. If equal to 1.0, '
              'the dominant-BP capture in the per-attribution loop was removed.',
        );
        expect(
          (json['novelty_mult'] as double),
          isNot(closeTo(1.0, 1e-6)),
          reason:
              'novelty_mult at sv=15 must be < 1.0 (exp decay). '
              'A value of 1.0 indicates the buggy initial-value was used.',
        );

        // cap_mult at weekly_vol=0 stays at 1.0, which is correct.
        expect(
          (json['cap_mult'] as double),
          closeTo(1.0, 1e-9),
          reason: 'cap_mult at weekly_vol=0 must be 1.0',
        );
      },
    );

    test('toJson() — cap_mult is non-trivial when weekly volume exceeds cap '
        '(regression PR#252 payload parity: cap_mult = 0.3 past the cap)', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 5,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 15, // at-cap → cap_mult = 0.3
        difficultyMult: 1.0,
      );
      final json = r.toJson();

      expect(
        json.containsKey('cap_mult'),
        isTrue,
        reason: 'cap_mult must be present in xp_events payload',
      );
      // Phase 24d: weekly_vol >= 15 sets → cap_mult = 0.3 (overCapMultiplier).
      expect(
        (json['cap_mult'] as double),
        closeTo(0.3, 1e-9),
        reason:
            'cap_mult at weekly_vol=15 must be 0.3 (overCapMultiplier). '
            'A value of 1.0 indicates the cap computation was skipped.',
      );
      expect(
        (json['cap_mult'] as double),
        isNot(closeTo(1.0, 1e-6)),
        reason:
            'cap_mult at weekly_vol=15 must NOT be 1.0 — the cap fires here.',
      );
    });
  });

  group('Boundary + edge cases', () {
    test(
      'zero weight + zero reps → set_xp = 1.0^0.60 × 1 × 1 × 1 × 1 × 1 = 1.0',
      () {
        final r = XpCalculator.computeSetXp(
          weightKg: 0,
          reps: 0,
          peakLoad: 0,
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
          difficultyMult: 1.0,
        );
        expect(r.volumeLoad, 1.0);
        expect(r.baseXp, 1.0);
        expect(r.setXp, 1.0); // 1 × 1 × 1 × 1 × 1 × 1
      },
    );

    test('massive weight does not produce infinity or NaN', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 9999,
        reps: 20,
        peakLoad: 9999,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.0,
      );
      expect(r.setXp.isFinite, isTrue);
      expect(r.setXp, greaterThan(0));
    });

    test('past the weekly cap with high session volume compounds', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 5,
        peakLoad: 100,
        sessionVolumeForBodyPart: 30, // deep into novelty decay
        weeklyVolumeForBodyPart: 30, // past cap
        difficultyMult: 1.0,
      );
      // novelty = exp(-2) ≈ 0.1353, cap = 0.3 (Phase 24d) → set_xp << base
      final base = XpCalculator.baseXp(
        XpCalculator.volumeLoad(weightKg: 100, reps: 5),
      );
      expect(r.setXp, lessThan(base * 0.10));
    });

    test('all multipliers at unity → set_xp == base_xp × intensity', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8, // intensity 1.0
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.0,
      );
      expect(r.intensityMult, 1.0);
      expect(r.strengthMult, 1.0);
      expect(r.noveltyMult, 1.0);
      expect(r.capMult, 1.0);
      expect(r.difficultyMult, 1.0);
      expect(r.setXp, closeTo(r.baseXp, _eps));
    });
  });

  // ---------------------------------------------------------------------------
  // Phase 24a — difficulty_mult parameter semantics
  //
  // These tests are NOT fixture-driven: they pin the multiplier contract
  // independent of the fixture. They are the canary that catches a Phase D
  // (SQL RPC) or Phase E (Python sim + fixture regen) drift later.
  // ---------------------------------------------------------------------------
  group('difficultyMult — parameter semantics', () {
    /// Same inputs at all three difficulty values must scale linearly:
    /// set_xp(d) / set_xp(1.0) == d. This pins difficulty_mult as the final,
    /// purely-multiplicative factor in the chain (no clamp inside
    /// `computeSetXp`, no interaction with other multipliers).
    test('at ceiling (1.25) produces 1.25× the XP of the same set at 1.0', () {
      final baseline = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.0,
      );
      final ceiling = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.25,
      );
      expect(ceiling.difficultyMult, 1.25);
      expect(
        ceiling.setXp,
        closeTo(baseline.setXp * 1.25, _eps),
        reason:
            'difficulty_mult must apply as a final linear scalar; '
            'baseline=${baseline.setXp}, ceiling=${ceiling.setXp}, '
            'expected ratio 1.25, got ${ceiling.setXp / baseline.setXp}',
      );
      // Other components unchanged — the multiplier touches setXp only.
      expect(ceiling.volumeLoad, baseline.volumeLoad);
      expect(ceiling.baseXp, baseline.baseXp);
      expect(ceiling.intensityMult, baseline.intensityMult);
      expect(ceiling.strengthMult, baseline.strengthMult);
      expect(ceiling.noveltyMult, baseline.noveltyMult);
      expect(ceiling.capMult, baseline.capMult);
    });

    test('at floor (0.85) produces 0.85× the XP of the same set at 1.0', () {
      final baseline = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 1.0,
      );
      final floor = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8,
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
        difficultyMult: 0.85,
      );
      expect(floor.difficultyMult, 0.85);
      expect(
        floor.setXp,
        closeTo(baseline.setXp * 0.85, _eps),
        reason:
            'baseline=${baseline.setXp}, floor=${floor.setXp}, '
            'expected ratio 0.85, got ${floor.setXp / baseline.setXp}',
      );
    });

    /// Default-1.0 invariant: a user-created exercise (or any unmapped
    /// default before Phase B's curated UPDATE) reads the column default
    /// 1.0 and must produce the **same** set_xp the formula would
    /// produce without difficulty_mult ever existing. This is the
    /// "no behavior change for unmapped exercises" pin.
    test(
      'difficultyMult: 1.0 produces XP byte-identical to the pre-24a chain',
      () {
        // Hand-compute the pre-24a chain explicitly so this test does NOT
        // delegate to computeSetXp itself (which would tautologically pass
        // even if difficulty_mult silently broke).
        const weight = 80.0;
        const reps = 5;
        const peak = 100.0;
        const sessionVol = 2.5;
        const weeklyVol = 8.0;

        final vl = XpCalculator.volumeLoad(weightKg: weight, reps: reps);
        final base = XpCalculator.baseXp(vl);
        final intensity = XpCalculator.intensityForReps(reps);
        final strength = XpCalculator.strengthMult(
          weightKg: weight,
          peakLoad: peak,
        );
        final novelty = XpCalculator.noveltyMult(sessionVol);
        final cap = XpCalculator.capMult(weeklyVol);
        final pre24aSetXp = base * intensity * strength * novelty * cap;

        final r = XpCalculator.computeSetXp(
          weightKg: weight,
          reps: reps,
          peakLoad: peak,
          sessionVolumeForBodyPart: sessionVol,
          weeklyVolumeForBodyPart: weeklyVol,
          difficultyMult: 1.0,
        );

        expect(r.difficultyMult, 1.0);
        expect(
          r.setXp,
          closeTo(pre24aSetXp, _eps),
          reason:
              'difficulty_mult: 1.0 must be a no-op; '
              'pre-24a chain = $pre24aSetXp, computeSetXp = ${r.setXp}',
        );
      },
    );

    test('floor and ceiling constants match the migration CHECK range', () {
      expect(XpCalculator.difficultyMultFloor, 0.85);
      expect(XpCalculator.difficultyMultCeiling, 1.25);
    });
  });

  // ---------------------------------------------------------------------------
  // Phase 29 v2 + 29.6 — new constants + helpers parity
  // ---------------------------------------------------------------------------

  group('Phase 29 v2 constants parity with Python sim', () {
    test('kEBonus / kEFloor / kECeil match fixture meta', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.kEBonus, meta['e_bonus']);
      expect(XpCalculator.kEFloor, meta['e_floor']);
      expect(XpCalculator.kECeil, meta['e_ceil']);
      expect(XpCalculator.kEBonus, 0.8);
      expect(XpCalculator.kEFloor, 35.0);
      expect(XpCalculator.kECeil, 55.0);
    });

    test('kNfIntensityBonus + kNfTargetThreshold match fixture meta', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.kNfIntensityBonus, meta['nf_intensity_bonus']);
      expect(XpCalculator.kNfTargetThreshold, meta['nf_target_threshold']);
      expect(XpCalculator.kNfIntensityBonus, 0.10);
      expect(XpCalculator.kNfTargetThreshold, 0.85);
    });

    test('kFrequencyMultTable matches fixture meta '
        '([1.00, 1.06, 1.10, 1.06, 1.00])', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      final expected = (meta['frequency_mult_table'] as List<dynamic>)
          .map((e) => (e as num).toDouble())
          .toList();
      expect(XpCalculator.kFrequencyMultTable, expected);
      expect(XpCalculator.kFrequencyMultTable, [1.00, 1.06, 1.10, 1.06, 1.00]);
    });
  });

  group('absStrengthPremium — fixture parity', () {
    test('every fixture case matches within $_eps', () {
      final cases = fixtures['abs_strength_premium'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final T = (c['implied_tier'] as num).toDouble();
        final expectedPrem = (c['abs_strength_premium'] as num).toDouble();
        final expectedFrac = (c['frac'] as num).toDouble();
        expect(
          absStrengthPremium(T),
          closeTo(expectedPrem, _eps),
          reason: 'absStrengthPremium(T=$T)',
        );
        expect(
          absStrengthPremiumFrac(T),
          closeTo(expectedFrac, _eps),
          reason: 'absStrengthPremiumFrac(T=$T)',
        );
      }
    });

    test(
      'canonical pins — T=35 → 1.0, T=55 → 1.8, T=20 → 1.0 (below floor)',
      () {
        expect(absStrengthPremium(35.0), 1.0);
        expect(absStrengthPremium(55.0), closeTo(1.8, _eps));
        expect(absStrengthPremium(20.0), 1.0);
        // Mid-band: T=45 → frac=0.5 → premium=1.4
        expect(absStrengthPremium(45.0), closeTo(1.4, _eps));
      },
    );
  });

  group('tierDiffMult — fixture parity', () {
    test('every fixture case matches within $_eps', () {
      final cases = fixtures['tier_diff_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final T = (c['implied_tier'] as num).toDouble();
        final R = (c['current_rank'] as num).toDouble();
        final expected = (c['tier_diff_mult'] as num).toDouble();
        expect(
          tierDiffMult(impliedTier: T, currentRank: R),
          closeTo(expected, _eps),
          reason: 'tierDiffMult(T=$T, R=$R)',
        );
      }
    });

    test('canonical pin — T=R=1 produces 1.0 exactly', () {
      expect(
        tierDiffMult(impliedTier: 1.0, currentRank: 1.0),
        closeTo(1.0, _eps),
      );
    });

    test('floor — weak lift @ high rank clamps to kTierDiffMin', () {
      expect(tierDiffMult(impliedTier: 5.0, currentRank: 25.0), kTierDiffMin);
    });

    test('T=0 early-exits at 1.0 (no tier signal)', () {
      expect(tierDiffMult(impliedTier: 0.0, currentRank: 5.0), 1.0);
    });
  });

  group('overloadMult — fixture parity', () {
    /// The Dart calculator's `overloadMult` is band-agnostic — band
    /// matching is the repository's job (it looks up
    /// `exercise_peak_loads_by_rep_range` keyed by `(user, exercise,
    /// rep_band)` and only passes the prior if there's a same-band
    /// record). Mirror that here: derive the rep band from
    /// current + prior reps and pass null priors when they differ.
    String repBand(int reps) {
      if (reps <= 4) return 'heavy';
      if (reps <= 7) return 'strength';
      if (reps <= 12) return 'hypertrophy';
      return 'endurance';
    }

    test('every fixture case matches', () {
      final cases = fixtures['overload_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final w = (c['weight_kg'] as num).toDouble();
        final r = c['reps'] as int;
        final priorW = c['prior_weight_kg'] == null
            ? null
            : (c['prior_weight_kg'] as num).toDouble();
        final priorR = c['prior_reps'] as int?;
        final expected = (c['overload_mult'] as num).toDouble();
        // Cross-band prior → null at the repository boundary; Python
        // sim's helper returns 1.0 in that case (band-keyed lookup miss).
        final crossBand = priorR != null && repBand(r) != repBand(priorR);
        expect(
          XpCalculator.overloadMult(
            weightKg: w,
            reps: r,
            priorWeight: crossBand ? null : priorW,
            priorReps: crossBand ? null : priorR,
          ),
          closeTo(expected, _eps),
          reason:
              '[${c['name']}] overloadMult(w=$w, r=$r, '
              'prior=($priorW, $priorR), crossBand=$crossBand)',
        );
      }
    });

    test('canonical pins — new weight PR → 1.15, volume PR → 1.10, '
        'modest → 1.05, no change → 1.00', () {
      // New weight PR
      expect(
        XpCalculator.overloadMult(
          weightKg: 85,
          reps: 5,
          priorWeight: 80,
          priorReps: 5,
        ),
        1.15,
      );
      // Volume PR at same load
      expect(
        XpCalculator.overloadMult(
          weightKg: 80,
          reps: 8,
          priorWeight: 80,
          priorReps: 5,
        ),
        1.10,
      );
      // Reps up + weight down
      expect(
        XpCalculator.overloadMult(
          weightKg: 75,
          reps: 8,
          priorWeight: 80,
          priorReps: 5,
        ),
        1.05,
      );
      // No change
      expect(
        XpCalculator.overloadMult(
          weightKg: 80,
          reps: 5,
          priorWeight: 80,
          priorReps: 5,
        ),
        1.0,
      );
      // No prior
      expect(XpCalculator.overloadMult(weightKg: 80, reps: 5), 1.0);
    });
  });

  group('frequencyMult — fixture parity', () {
    test('every fixture case matches', () {
      final cases = fixtures['frequency_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final n = c['session_count'] as int;
        final expected = (c['frequency_mult'] as num).toDouble();
        expect(
          XpCalculator.frequencyMult(n),
          closeTo(expected, _eps),
          reason: 'frequencyMult($n)',
        );
      }
    });

    test('peak at session 3 (1.10); endpoints flat at 1.00', () {
      expect(XpCalculator.frequencyMult(1), 1.00);
      expect(XpCalculator.frequencyMult(2), 1.06);
      expect(XpCalculator.frequencyMult(3), 1.10);
      expect(XpCalculator.frequencyMult(4), 1.06);
      expect(XpCalculator.frequencyMult(5), 1.00);
      // Out-of-range → clamped
      expect(XpCalculator.frequencyMult(0), 1.00);
      expect(XpCalculator.frequencyMult(100), 1.00);
    });
  });

  group('nearFailureInferred — fixture parity', () {
    test('every fixture case matches', () {
      final cases = fixtures['near_failure_inferred'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final actual = c['actual_reps'] as int;
        final target = c['target_reps'] as int?;
        final expected = c['near_failure_inferred'] as bool;
        expect(
          XpCalculator.nearFailureInferred(
            actualReps: actual,
            targetReps: target,
          ),
          expected,
          reason:
              '[${c['name']}] nearFailureInferred(actual=$actual, '
              'target=$target)',
        );
      }
    });

    test('canonical pin — 10×0.85 = 8.5 → 9 reps NOT inferred, '
        '8 reps inferred', () {
      expect(
        XpCalculator.nearFailureInferred(actualReps: 9, targetReps: 10),
        false,
      );
      expect(
        XpCalculator.nearFailureInferred(actualReps: 8, targetReps: 10),
        true,
      );
    });

    test('target NULL or 0 — never inferred (defensive)', () {
      expect(
        XpCalculator.nearFailureInferred(actualReps: 1, targetReps: null),
        false,
      );
      expect(
        XpCalculator.nearFailureInferred(actualReps: 1, targetReps: 0),
        false,
      );
    });
  });

  group('intensityWithNearFailure — near-failure +0.10 additive', () {
    test('reps=5 base 1.20 → +0.10 = 1.30 when nf=true', () {
      expect(
        XpCalculator.intensityWithNearFailure(reps: 5, nearFailure: true),
        closeTo(1.30, _eps),
      );
      expect(
        XpCalculator.intensityWithNearFailure(reps: 5, nearFailure: false),
        closeTo(1.20, _eps),
      );
    });

    test('reps=20 base 0.80 → +0.10 = 0.90 when nf=true', () {
      expect(
        XpCalculator.intensityWithNearFailure(reps: 20, nearFailure: true),
        closeTo(0.90, _eps),
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Phase 29 v2 — full 11-multiplier chain (set_xp_v2 fixture)
  //
  // 94 cases. Tolerance is 1e-4 absolute per the brief — the cumulative
  // chain compounds float rounding more than the component-level tests.
  // ---------------------------------------------------------------------------
  group('computeSetXp — Phase 29 v2 set_xp_v2 fixture parity', () {
    const v2Eps = 1e-4;

    test('every set_xp_v2 case matches within $v2Eps absolute', () {
      final cases = fixtures['set_xp_v2'] as List<dynamic>;
      expect(cases.length, 94, reason: 'expected 94 set_xp_v2 oracle rows');

      var failed = 0;
      var firstFailureMsg = '';

      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final inputs = c['inputs'] as Map<String, dynamic>;
        final components = c['components'] as Map<String, dynamic>;

        final exercise = inputs['exercise'] as String;
        final weight = (inputs['weight_kg'] as num).toDouble();
        final reps = inputs['reps'] as int;
        final peak = (inputs['peak_load'] as num).toDouble();
        final sv = (inputs['session_volume_prior'] as num).toDouble();
        final wv = (inputs['weekly_volume_prior'] as num).toDouble();
        final diff = (inputs['difficulty_mult'] as num).toDouble();
        final bw = (inputs['bodyweight_kg'] as num).toDouble();
        final female = inputs['gender_female'] as bool;
        final ranks = (inputs['current_ranks'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(k, (v as num).toInt()),
        );
        final dominantPart = inputs['dominant_part'] as String;
        final currentRank = ranks[dominantPart]?.toDouble() ?? 1.0;
        final nf = inputs['near_failure'] as bool;
        final target = inputs['target_reps'] as int?;
        final bpSessionCount = inputs['bp_session_count'] as int;
        final usesBw = inputs['uses_bodyweight_load'] as bool;
        final bwRatio = inputs['bodyweight_load_ratio'] == null
            ? null
            : (inputs['bodyweight_load_ratio'] as num).toDouble();

        // Phase 29 v2: the Dart calculator is bodyweight-agnostic. The
        // caller pre-converts entered_weight → effective_load. For
        // bodyweight exercises, that's `entered + bw × ratio`. For
        // non-BW, that's just entered.
        final effLoad = usesBw ? weight + bw * (bwRatio ?? 1.0) : weight;

        // Reconstruct the prior best for overload_mult — the fixture
        // stores `best_by_band_prior` as a 2-list of [(exercise, band),
        // (prior_w, prior_r)] when there is one.
        double? priorW;
        int? priorR;
        final priorRaw = inputs['best_by_band_prior'];
        if (priorRaw != null) {
          // JSON encodes the tuple as a 2-element list:
          // [[exercise_key, band_key], [prior_w, prior_r]]
          final priorList = priorRaw as List<dynamic>;
          final priorTuple = priorList[1] as List<dynamic>;
          priorW = (priorTuple[0] as num).toDouble();
          priorR = (priorTuple[1] as num).toInt();
        }

        // Compute implied tier independently — matches the fixture's
        // expected value (also stored at components.lift_implied_tier).
        final tier = impliedTier(
          exercise: exercise,
          weightKg: weight,
          reps: reps,
          bodyweightKg: bw,
          gender: female ? LiftGender.female : LiftGender.male,
        );

        // Phase 29 v2 chain produces per-(set, body-part) XP, not a
        // single per-set total. The Python sim's `compute_set_xp` runs
        // the per-bp inner loop where each body part sees its OWN
        // novelty_count and weekly_count. The fixture seeds only the
        // dominant body part's session_volume / weekly_volume
        // (`session_volume_seed_bp`); every other body part starts at
        // 0/0 → novelty_mult = 1.0, cap_mult = 1.0 for those.
        //
        // For parity we iterate the attribution map and call the
        // calculator once per body part with the correct per-bp
        // session/weekly volume.
        final seedBp = inputs['session_volume_seed_bp'] as String;
        final awardedPerBp = (c['awarded_per_bp'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(k, (v as num).toDouble()),
        );
        final attribution = (inputs['attribution'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(k, (v as num).toDouble()),
        );

        var allMatch = true;
        SetXpComponents? lastResult;
        for (final entry in attribution.entries) {
          final bp = entry.key;
          final share = entry.value;
          // Only the seed body part carries the seeded prior; every
          // other body part starts fresh in this synthetic fixture.
          final perBpSv = (bp == seedBp) ? sv : 0.0;
          final perBpWv = (bp == seedBp) ? wv : 0.0;

          final result = XpCalculator.computeSetXp(
            weightKg: effLoad,
            reps: reps,
            peakLoad: peak,
            sessionVolumeForBodyPart: perBpSv,
            weeklyVolumeForBodyPart: perBpWv,
            difficultyMult: diff,
            impliedTier: tier,
            currentRank: currentRank,
            priorBandWeight: priorW,
            priorBandReps: priorR,
            sessionsThisWeekForBodyPart: bpSessionCount,
            nearFailure: nf,
            targetReps: target,
          );
          lastResult = result;

          final dartAward = result.setXp * share;
          final pyAward = awardedPerBp[bp] ?? 0.0;
          if ((dartAward - pyAward).abs() > v2Eps) {
            allMatch = false;
            if (firstFailureMsg.isEmpty) {
              firstFailureMsg =
                  '[${c['name']}] bp=$bp '
                  'dart=$dartAward py=$pyAward '
                  'delta=${(dartAward - pyAward).abs()} '
                  '(set_xp=${result.setXp})';
            }
          }
        }

        // Also pin individual component fields so divergence reports a
        // specific multiplier rather than just the total. Use the last
        // computed result; per-bp differs only in novelty + cap.
        final expectedTier = (components['lift_implied_tier'] as num)
            .toDouble();
        if (lastResult != null &&
            (lastResult.impliedTier - expectedTier).abs() > _eps) {
          failed++;
          if (firstFailureMsg.isEmpty) {
            firstFailureMsg =
                '[${c['name']}] implied_tier dart='
                '${lastResult.impliedTier} py=$expectedTier';
          }
        }
        if (!allMatch) failed++;
      }

      expect(
        failed,
        0,
        reason:
            'Phase 29 v2 parity failed for $failed/94 cases. '
            'First failure: $firstFailureMsg',
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Phase Vitality-3 — strength conditioning XP-gate
  // ---------------------------------------------------------------------------
  group('vitalityMult — strength conditioning gate pure core', () {
    const eps = 1e-4;

    test('floor constant is 0.50 (the gentler comeback floor, D1)', () {
      expect(XpCalculator.strengthVitalityFloor, 0.50);
    });

    test('strength_vitality_mult fixture rows match within $eps', () {
      final cases = fixtures['strength_vitality_mult'] as List<dynamic>;
      expect(cases, hasLength(7), reason: 'expected 7 gate-core rows');
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final inputs = c['inputs'] as Map<String, dynamic>;
        final vmult = XpCalculator.vitalityMult(
          ewma: (inputs['vitality_ewma'] as num).toDouble(),
          refPeak: (inputs['vitality_ref_peak'] as num).toDouble(),
        );
        expect(
          vmult,
          closeTo((c['vitality_mult'] as num).toDouble(), eps),
          reason: 'vitality_mult mismatch for ${c['name']}',
        );
      }
    });

    test('refPeak <= 0 is a no-op (vmult 1.0) — un-conditioned prior', () {
      expect(XpCalculator.vitalityMult(ewma: 0.0, refPeak: 0.0), 1.0);
      expect(XpCalculator.vitalityMult(ewma: 500.0, refPeak: -1.0), 1.0);
    });

    test(
      'fully lapsed (vpct 0) earns exactly the floor; full charge earns 1.0',
      () {
        expect(
          XpCalculator.vitalityMult(ewma: 0.0, refPeak: 1000.0),
          closeTo(0.50, eps),
        );
        expect(
          XpCalculator.vitalityMult(ewma: 1000.0, refPeak: 1000.0),
          closeTo(1.0, eps),
        );
        // ewma above refPeak clamps to vpct 1.0 → vmult 1.0 (defensive).
        expect(
          XpCalculator.vitalityMult(ewma: 1500.0, refPeak: 1000.0),
          closeTo(1.0, eps),
        );
      },
    );
  });

  group('computeSetXp — Phase Vitality-3 gated per-bp parity (set_xp_gated)', () {
    const eps = 1e-4;

    test('every set_xp_gated case scales EACH body part by ITS OWN vmult', () {
      final cases = fixtures['set_xp_gated'] as List<dynamic>;
      expect(cases, hasLength(3), reason: 'expected 3 multi-bp gated rows');

      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final inputs = c['inputs'] as Map<String, dynamic>;
        final name = c['name'] as String;

        final exercise = inputs['exercise'] as String;
        final weight = (inputs['weight_kg'] as num).toDouble();
        final reps = inputs['reps'] as int;
        final peak = (inputs['peak_load'] as num).toDouble();
        final diff = (inputs['difficulty_mult'] as num).toDouble();
        final bw = (inputs['bodyweight_kg'] as num).toDouble();
        final female = inputs['gender_female'] as bool;
        final dominantPart = inputs['dominant_part'] as String;
        final ranks = (inputs['current_ranks'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(k, (v as num).toInt()),
        );
        final currentRank = ranks[dominantPart]?.toDouble() ?? 1.0;

        final tier = impliedTier(
          exercise: exercise,
          weightKg: weight,
          reps: reps,
          bodyweightKg: bw,
          gender: female ? LiftGender.female : LiftGender.male,
        );

        final attribution = (inputs['attribution'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(k, (v as num).toDouble()),
        );
        final ewmaByBp = inputs['vitality_ewma_by_bp'] as Map<String, dynamic>;
        final refPeakByBp =
            inputs['vitality_ref_peak_by_bp'] as Map<String, dynamic>;
        final vmultByBp = inputs['vmult_by_bp'] as Map<String, dynamic>;
        final awardedPerBp = (c['awarded_per_bp'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(k, (v as num).toDouble()),
        );
        final ungatedPerBp = (c['ungated_per_bp'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(k, (v as num).toDouble()),
        );

        for (final entry in attribution.entries) {
          final bp = entry.key;
          final share = entry.value;

          // The per-bp conditioning → the per-bp gate factor. This is the
          // caller's job in the live path: derive THIS body part's vmult and
          // pass it for THIS body part's fan-out call.
          final vmult = XpCalculator.vitalityMult(
            ewma: (ewmaByBp[bp] as num).toDouble(),
            refPeak: (refPeakByBp[bp] as num).toDouble(),
          );
          expect(
            vmult,
            closeTo((vmultByBp[bp] as num).toDouble(), eps),
            reason: '$name/$bp: per-bp vmult mismatch',
          );

          final gated = XpCalculator.computeSetXp(
            weightKg: weight,
            reps: reps,
            peakLoad: peak,
            sessionVolumeForBodyPart: 0.0,
            weeklyVolumeForBodyPart: 0.0,
            difficultyMult: diff,
            impliedTier: tier,
            currentRank: currentRank,
            vitalityMult: vmult,
          );
          final gatedAward = gated.setXp * share;
          expect(
            gatedAward,
            closeTo(awardedPerBp[bp]!, eps),
            reason: '$name/$bp: gated award mismatch (per-bp keying)',
          );

          // The ungated path (vitalityMult default 1.0) must reproduce the
          // ungated oracle — proving the gate is the ONLY difference and that
          // gated == ungated × this bp's vmult.
          final ungated = XpCalculator.computeSetXp(
            weightKg: weight,
            reps: reps,
            peakLoad: peak,
            sessionVolumeForBodyPart: 0.0,
            weeklyVolumeForBodyPart: 0.0,
            difficultyMult: diff,
            impliedTier: tier,
            currentRank: currentRank,
          );
          final ungatedAward = ungated.setXp * share;
          expect(
            ungatedAward,
            closeTo(ungatedPerBp[bp]!, eps),
            reason: '$name/$bp: ungated award mismatch',
          );
          expect(
            gatedAward,
            closeTo(ungatedAward * vmult, eps),
            reason: '$name/$bp: gated must equal ungated × per-bp vmult',
          );
        }
      }
    });

    test('the dominant body part is NOT the gate key — a lapsed dominant bp '
        'with charged minor bps gates only the dominant', () {
      // squat: legs (dominant, 0.80) lapsed → 0.50; back/core (minor) full → 1.0.
      final cases = fixtures['set_xp_gated'] as List<dynamic>;
      final squat = cases.cast<Map<String, dynamic>>().firstWhere(
        (c) => c['name'] == 'squat_dominant_lapsed_minor_charged',
      );
      final vmultByBp =
          (squat['inputs'] as Map<String, dynamic>)['vmult_by_bp']
              as Map<String, dynamic>;
      expect((vmultByBp['legs'] as num).toDouble(), closeTo(0.50, eps));
      expect((vmultByBp['core'] as num).toDouble(), closeTo(1.0, eps));
      expect((vmultByBp['back'] as num).toDouble(), closeTo(1.0, eps));
    });
  });
}
