/// Family 6 (AW-EX-F-BR1-02) — `_generateWorkoutName` locale leak.
///
/// Pre-PR: the date format was hard-coded to `DateFormat('EEE MMM d')` (en
/// only) and the prefix was the literal `'Workout — '`. A pt-BR session
/// that started without a name was saved as e.g. `'Workout — Wed May 7'`,
/// which then displayed forever in pt-BR sessions.
///
/// Post-PR: locale is read at GENERATION TIME via
/// `ref.read(localeProvider).languageCode`. The prefix flows through
/// `l10n.workoutDefaultName(date)` and `DateFormat` is instantiated with
/// that language code so the date string honors locale conventions
/// (e.g. pt: `'Treino — qua 7 mai'`). The generated name is persisted
/// once and never re-rendered — matching the inline rationale at
/// `active_workout_notifier.dart:272-277`.
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:mocktail/mocktail.dart';
import 'package:repsaga/core/data/base_repository.dart';
import 'package:repsaga/core/l10n/locale_provider.dart';
import 'package:repsaga/features/analytics/data/analytics_repository.dart';
import 'package:repsaga/features/analytics/data/models/analytics_event.dart';
import 'package:repsaga/features/analytics/providers/analytics_providers.dart';
import 'package:repsaga/features/auth/data/auth_repository.dart';
import 'package:repsaga/features/auth/providers/auth_providers.dart';
import 'package:repsaga/features/workouts/data/workout_local_storage.dart';
import 'package:repsaga/features/workouts/data/workout_repository.dart';
import 'package:repsaga/features/workouts/models/active_workout_state.dart';
import 'package:repsaga/features/workouts/models/workout.dart';
import 'package:repsaga/features/workouts/providers/workout_providers.dart';
import 'package:supabase_flutter/supabase_flutter.dart' show User;

import '../../../../helpers/stub_locale_notifier.dart';

class _MockWorkoutRepository extends Mock implements WorkoutRepository {}

class _MockWorkoutLocalStorage extends Mock implements WorkoutLocalStorage {}

class _MockAuthRepository extends Mock implements AuthRepository {}

class _FakeActiveWorkoutState extends Fake implements ActiveWorkoutState {}

class _FakeWorkout extends Fake implements Workout {}

User _fakeUser({String id = 'user-test-name'}) => User(
  id: id,
  appMetadata: const {},
  userMetadata: const {},
  aud: 'authenticated',
  email: 'name@test.com',
  createdAt: DateTime(2026).toIso8601String(),
);

/// No-op analytics repo — avoids hitting `Supabase.instance` in unit tests.
class _NoopAnalyticsRepository extends BaseRepository
    implements AnalyticsRepository {
  const _NoopAnalyticsRepository();

  @override
  Future<void> insertEvent({
    required String userId,
    required AnalyticsEvent event,
    required String? platform,
    required String? appVersion,
  }) async {}
}

Workout _makeWorkout({String id = 'w-1', String? name}) => Workout(
  id: id,
  userId: 'user-test-name',
  name: name ?? 'Generated by notifier',
  startedAt: DateTime.now().toUtc(),
  isActive: true,
  createdAt: DateTime.now().toUtc(),
);

({
  ProviderContainer container,
  _MockWorkoutRepository repo,
  _MockWorkoutLocalStorage storage,
  _MockAuthRepository auth,
})
_makeAsyncContainer({required Locale locale}) {
  final repo = _MockWorkoutRepository();
  final storage = _MockWorkoutLocalStorage();
  final auth = _MockAuthRepository();

  when(() => storage.loadActiveWorkout()).thenReturn(null);
  when(() => storage.saveActiveWorkout(any())).thenAnswer((_) async {});

  final container = ProviderContainer(
    overrides: [
      workoutRepositoryProvider.overrideWithValue(repo),
      workoutLocalStorageProvider.overrideWithValue(storage),
      authRepositoryProvider.overrideWithValue(auth),
      analyticsRepositoryProvider.overrideWithValue(
        const _NoopAnalyticsRepository(),
      ),
      // The workout-name fix reads locale at generation time. Override
      // localeProvider with a stub that returns the desired test locale.
      localeProvider.overrideWith(() => StubLocaleNotifier(locale)),
    ],
  );

  return (container: container, repo: repo, storage: storage, auth: auth);
}

void main() {
  setUpAll(() async {
    // `DateFormat('EEE MMM d', 'pt')` requires the pt locale data to be
    // registered up-front. This is the pattern used by other intl-using
    // tests in the suite.
    await initializeDateFormatting();
    registerFallbackValue(_FakeActiveWorkoutState());
    registerFallbackValue(_FakeWorkout());
  });

  group('_generateWorkoutName locale awareness (Family 6)', () {
    test(
      'en locale: auto-generated name starts with "Workout — " and contains a date',
      () async {
        final (:container, :repo, :storage, :auth) = _makeAsyncContainer(
          locale: const Locale('en'),
        );
        addTearDown(container.dispose);

        when(() => auth.currentUser).thenReturn(_fakeUser());
        when(
          () => repo.createActiveWorkout(
            userId: any(named: 'userId'),
            name: any(named: 'name'),
          ),
        ).thenAnswer((_) async => _makeWorkout());

        await container.read(activeWorkoutProvider.future);
        await container.read(activeWorkoutProvider.notifier).startWorkout();

        final captured = verify(
          () => repo.createActiveWorkout(
            userId: any(named: 'userId'),
            name: captureAny(named: 'name'),
          ),
        ).captured;
        final name = captured.first as String;

        expect(
          name,
          startsWith('Workout — '),
          reason:
              'en locale must produce the en prefix '
              '(l10n.workoutDefaultName).',
        );
        expect(
          name.length,
          greaterThan('Workout — '.length),
          reason: 'date must be appended after the prefix.',
        );
      },
    );

    test(
      'pt locale: auto-generated name starts with "Treino — " (NOT the en prefix)',
      () async {
        final (:container, :repo, :storage, :auth) = _makeAsyncContainer(
          locale: const Locale('pt'),
        );
        addTearDown(container.dispose);

        when(() => auth.currentUser).thenReturn(_fakeUser());
        when(
          () => repo.createActiveWorkout(
            userId: any(named: 'userId'),
            name: any(named: 'name'),
          ),
        ).thenAnswer((_) async => _makeWorkout());

        await container.read(activeWorkoutProvider.future);
        await container.read(activeWorkoutProvider.notifier).startWorkout();

        final captured = verify(
          () => repo.createActiveWorkout(
            userId: any(named: 'userId'),
            name: captureAny(named: 'name'),
          ),
        ).captured;
        final name = captured.first as String;

        // Pin the localized prefix. The date portion is locale-formatted so
        // we don't pin its exact spelling — the prefix is the load-bearing
        // contract. (Pre-fix this would have been "Workout — Wed May 7"
        // even on a pt-BR device.)
        expect(
          name,
          startsWith('Treino — '),
          reason:
              'pt locale must produce the pt prefix; the en prefix here is '
              'the AW-EX-F-BR1-02 leak.',
        );
        expect(
          name.contains('Workout'),
          isFalse,
          reason: 'pt-locale generated name must not leak the English prefix.',
        );
      },
    );

    test(
      'pt locale: date portion is non-empty and uses the pt locale formatter',
      () async {
        final (:container, :repo, :storage, :auth) = _makeAsyncContainer(
          locale: const Locale('pt'),
        );
        addTearDown(container.dispose);

        when(() => auth.currentUser).thenReturn(_fakeUser());
        when(
          () => repo.createActiveWorkout(
            userId: any(named: 'userId'),
            name: any(named: 'name'),
          ),
        ).thenAnswer((_) async => _makeWorkout());

        await container.read(activeWorkoutProvider.future);
        await container.read(activeWorkoutProvider.notifier).startWorkout();

        final captured = verify(
          () => repo.createActiveWorkout(
            userId: any(named: 'userId'),
            name: captureAny(named: 'name'),
          ),
        ).captured;
        final name = captured.first as String;
        final datePortion = name.substring('Treino — '.length);

        expect(
          datePortion,
          isNotEmpty,
          reason: 'date portion must be appended.',
        );
        // Sanity check: under pt, weekday abbreviations are e.g.
        // qua/seg/sex — distinct from en weekday abbreviations
        // (Wed/Mon/Fri). We don't pin the exact day (depends on test run
        // date) but we DO pin that the pt formatter ran by checking the
        // string contains at least one lowercase letter (en abbreviations
        // are typically capitalized like "Wed" / "May" with `EEE MMM d`).
        // The pt formatter produces lowercase (e.g. "qua 7 mai").
        expect(
          datePortion.toLowerCase(),
          datePortion,
          reason:
              'pt DateFormat output should be lowercase; if this fails the '
              'formatter fell back to the en-default and the locale is '
              'leaking.',
        );
      },
    );
  });
}
